version: '3.4'

services:
  health.api:
    image: ${DOCKER_REGISTRY-}healthapi
    build:
      context: .
      dockerfile: Health.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  health.database:
    image: postgres:latest
    container_name: health.database
    environment:
      - POSTGRES_DB=health
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/health-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  proxy:
    image: nginx:mainline