services:
  health.cache:
    image: redis
    container_name: health.cache
    restart: always
    ports:
      - "6379:6379"
  
  health.database:
    image: postgres:latest
    container_name: health.database
    environment:
      - POSTGRES_DB=healthdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/health-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  health.console:
    image: ${DOCKER_REGISTRY-}health.console
    container_name: health.console
    build:
      context: .
      dockerfile: Health.ConsoleCommand/Dockerfile
    stdin_open: true
    tty: true        
  