services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080"
    volumes:
      - ./wwwroot:/app/wwwroot
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  health.cache:
    image: redis
    container_name: health.cache
    restart: always
    ports:
      - "6379:6379"
  
  health.database:
    image: postgres:latest
    container_name: health.database
    environment:
      - POSTGRES_DB=healthdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/health-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"